SELECT * FROM EMP_TEMP2;

CREATE TABLE EMP_TEMP2
AS (SELECT * FROM EMP);

-- DELETE FROM 테이블_이름
-- [WHERE 삭제할 대상 행을 위한 조건식];

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER'
;

-- WHERE절에 서브쿼리 사용하기

DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
				FROM EMP_TEMP2 E, SALGRADE S
				WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
				AND S.GRADE = 3
				AND DEPTNO = 30)
;

-- 데이터 모두 삭제
DELETE FROM EMP_TEMP2;

