SELECT AVG(SAL), '10' AS DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT AVG(SAL), '20' AS DEPTNO
FROM EMP
WHERE DEPTNO = 20
UNION ALL
SELECT AVG(SAL), '30' AS DEPTNO
FROM EMP
WHERE DEPTNO = 30;
-- 다중행 함수인 AVG함수 옆엔 부서 코드 열을 붙일 수 없어 부서번호를 직접 작성하여 별칭을 줌
-- 위와 아래는 같음
SELECT AVG(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;
