--Q1
SELECT DEPTNO, ROUND(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT
FROM EMP
GROUP BY DEPTNO
;

--Q2
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(JOB) >= 3
;

--Q3
SELECT TO_CHAR(HIREDATE, 'YYYY') HIRE_YEAR, DEPTNO, COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO
;

--Q4
SELECT NVL2(COMM, 'O', 'X') EXIST_COMM, COUNT(*) CNT
FROM EMP
GROUP BY NVL2(COMM, 'O', 'X')
;

--Q5
SELECT DEPTNO, TO_CHAR(HIREDATE, 'YYYY') HIRE_YEAR, MAX(SAL) MAX_SAL, SUM(SAL) SUM_SAL, AVG(SAL) AVG_SAL
FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY'))
;